naming:
  FunctionNaming:
    ignoreAnnotated:
      - 'Composable'
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'
complexity:
  LongParameterList:
    ignoreDefaultParameters: true
style:
  MagicNumber:
    ignorePropertyDeclaration: true
    ignoreEnums: true
  WildcardImport:
    excludeImports:
      - 'daniel.bertoldi.pokedex.data.api.response.*'
      - 'daniel.bertoldi.pokedex.domain.model.*'
      - 'androidx.compose.material.*'
      - 'androidx.compose.foundation.layout.*'
      - 'daniel.bertoldi.pokedex.presentation.model.*'
